<section class="fs_artist">
    Nom artiste: <span class="fs_artistName"></span>
    <br>
    Pays: <span class="fs_country"></span>
    <br>
    Site: <span class="fs_website"></span>
    <br>
    Facebook: <span class="fs_facebook"></span>
    <section class="albums">
        <h3>Albums</h3>
        <div class="fs_albums">
            <h4 class="fs_title"></h4>
            Ann&eacute;e: <span class="fs_year"></span>
            <br>
            Genre: <span class="fs_genre"></span>
            <br>
            Total pistes: <span class="fs_trackNumber"></span>
            <section class="tracks">
                <div class="fs_tracks">
                    <div class="fs_title"></div>
                    <div class="fs_duration"></div>
                    <button>Play</button>
                </div>
            </section>
        </div>
    </section>
</section>